import { Request, Response } from "express";
import { generateTryOn } from "./vton.service"; 

const UNIVERSAL_MODEL = "https://replicate.delivery/pbxt/KgwTlhCMvDagRrcVzZJbuozNJ8esPqiNAIJS3eMgHrYuHmW4/KakaoTalk_Photo_2024-04-04-21-44-45.png"; 

export const processVirtualTryOn = async (
  req: Request,
  res: Response,
): Promise<void> => {
  try {

    const { userImageUrl, garmentImageUrl, category, garmentDescription } = req.body;

    if (!userImageUrl || !garmentImageUrl) {
      res.status(400).json({
        success: false,
        error: "Both userImageUrl and garmentImageUrl are required",
      });
      return;
    }

    const safeCategory = category || "upper_body";
    const safeDescription = garmentDescription || "A professional photo of a garment";

    //Return a Image URL generated by the AI model based on the user image and garment image
    const generatedImageUrl = await generateTryOn(
      userImageUrl,
      garmentImageUrl,
      safeCategory,
      safeDescription
    );

    res.status(200).json({
      success: true,
      resultImage: generatedImageUrl,
    });

  } catch (error: any) {
    res.status(500).json({
      success: false,
      message: error.message || "Internal Server Error during VTON process",
    });
  }
};

export const processFashionStudio = async (
  req: Request,
  res: Response,
): Promise<void> => {
  try {
    
    const { garmentImageUrl, category, garmentDescription } = req.body;

    if (!garmentImageUrl) {
      res.status(400).json({ success: false, error: "garmentImageUrl is required" });
      return;
    }

    console.log("Received 1-Click Fashion Studio request for:", garmentImageUrl);

    const safeCategory = category || "upper_body";
    const safeDescription = garmentDescription || "A professional product photo";

    const finalImage = await generateTryOn(
        UNIVERSAL_MODEL, 
        garmentImageUrl,
        safeCategory,
        safeDescription
    );

    res.status(200).json({ success: true, url: finalImage });
    
  } catch (error: any) {
    console.error("Fashion Studio Controller Error:", error);
    res.status(500).json({ success: false, error: "Failed to generate fashion studio image" });
  }
};