"use client";

import { useState, useEffect } from "react";
import { useForm, Controller, SubmitHandler } from "react-hook-form";
import { useMutation } from "@tanstack/react-query";
// adjust the import path to where your axios instance file is located
import axiosInstance from '../../../../axiosInstance';
import ParentSelector from "../category/components/ParentSelector";
import BrandSelector from "../brand/components/BrandSelector";
import ImageUploader from "../../products/imagekit/components/ImageUploader";
import StockManager from "../stockmanager/components/StockManager";
import ColorSelector from "../colorselector/ColorSelector";

// --- Types ---
interface ProductImage {
  fileId: string;
  url: string;
}

interface Variant {
  size: string;
  stock: number;
}

// Match this to your form structure
interface ProductFormValues {
  name: string;
  description: string;
  price: number;
  stock: number;
  brand: string;
  categoryId: string;
  sizeType: string;
  variants: Variant[];
  colors: string[];
  images: ProductImage[];
  isNewArrival: boolean;
  discountType: "NONE" | "PERCENTAGE" | "FIXED";
  discountValue: number;
}

const INITIAL_DATA: ProductFormValues = {
  name: "",
  description: "",
  price: 0,
  stock: 0,
  brand: "",
  categoryId: "",
  sizeType: "Standard",
  variants: [],
  colors: [],
  images: [],
  isNewArrival: true,
  discountType: "NONE",
  discountValue: 0,
};

export default function AddProductPage() {
  const [baseName, setBaseName] = useState("");
  const [resetKey, setResetKey] = useState(0); // To force re-render of uncontrolled components on reset

  // 1. Setup React Hook Form
  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    reset,
    formState: { errors },
  } = useForm<ProductFormValues>({
    defaultValues: INITIAL_DATA,
  });

  // Watch values for real-time logic
  const watchedColors = watch("colors");
  const watchedPrice = watch("price");
  const watchedDiscountType = watch("discountType");
  const watchedDiscountValue = watch("discountValue");
  const currentName = watch("name");

  // 2. Setup TanStack Mutation
  const mutation = useMutation({
    mutationFn: async (newProduct: ProductFormValues) => {
      // axiosInstance automatically handles interceptors/refresh tokens
      const { data } = await axiosInstance.post("/api/products", newProduct);
      return data;
    },
    onSuccess: () => {
      reset(INITIAL_DATA);
      setBaseName("");
      setResetKey((prev) => prev + 1);
    },
  });

  // 3. Logic: Sync "Base Name" + "Color" -> "Product Name"
  useEffect(() => {
    const colorSuffix = watchedColors?.[0] ? ` - ${watchedColors[0]}` : "";
    setValue("name", baseName + colorSuffix);
  }, [baseName, watchedColors, setValue]);

  // 4. Logic: Calculate Discount (UI helper)
  const getDiscountedPrice = () => {
    const price = Number(watchedPrice) || 0;
    const val = Number(watchedDiscountValue) || 0;

    if (watchedDiscountType === "PERCENTAGE") {
      return price - price * (val / 100);
    } else if (watchedDiscountType === "FIXED") {
      return price - val;
    }
    return price;
  };

  const onSubmit: SubmitHandler<ProductFormValues> = (data) => {
    if (!data.categoryId) {
      alert("Please select a category"); // Or use toast
      return;
    }
    mutation.mutate(data);
  };

  return (
    <div className="max-w-4xl mx-auto p-8 bg-gray-50 min-h-screen">
      <h1 className="text-3xl font-bold text-gray-800 mb-8">Add New Product</h1>

      <form
        onSubmit={handleSubmit(onSubmit)}
        className="bg-white p-6 rounded-xl shadow-sm space-y-8"
      >
        {/* --- SECTION 1: BASIC DETAILS --- */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-700 border-b pb-2">
            Basic Details
          </h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="label">Product Name</label>
              <input
                type="text"
                className="input-field"
                value={baseName}
                onChange={(e) => setBaseName(e.target.value)}
                required
                placeholder="e.g. Night Dress"
              />
              <p className="text-xs text-gray-400 mt-1 h-4">
                {currentName !== baseName && (
                  <>
                    Saved as:{" "}
                    <span className="font-medium text-gray-600">
                      {currentName}
                    </span>
                  </>
                )}
              </p>
            </div>
            <div>
              <label className="label">SKU</label>
              <div className="p-3 bg-gray-100 border border-gray-300 rounded-md text-gray-500 text-sm select-none">
                🔒 Auto-generated by System
              </div>
            </div>
          </div>

          <div className="pt-2">
            {/* Color Selector wrapped in Controller */}
            <Controller
              name="colors"
              control={control}
              render={({ field }) => (
                <ColorSelector
                  key={`color-${resetKey}`}
                  selectedColor={field.value[0] || ""}
                  onChange={(colorName) => {
                    const newColors = colorName ? [colorName] : [];
                    field.onChange(newColors);
                  }}
                />
              )}
            />
          </div>

          <div>
            <label className="label">Description</label>
            <textarea
              {...register("description", { required: true })}
              rows={3}
              className="input-field"
            />
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-700 border-b pb-2">
              Media
            </h2>
            <ImageUploader
              key={`img-${resetKey}`}
              onUploadSuccess={(uploadedImages) =>
                setValue("images", uploadedImages)
              }
            />
          </div>
        </div>

        {/* --- SECTION 2: MARKETING & PRICING --- */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-700 border-b pb-2">
            Marketing & Pricing
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <label className="label">Original Price (LKR)</label>
                <input
                  type="number"
                  {...register("price", { required: true })}
                  className="input-field font-bold text-lg"
                />
              </div>

              {/* Brand Selector via Controller */}
              <Controller
                name="brand"
                control={control}
                render={({ field }) => (
                  <BrandSelector
                    key={`brand-${resetKey}`}
                    selectedBrand={field.value}
                    onChange={field.onChange}
                  />
                )}
              />
            </div>

            {/* OFFERS & FLAGS */}
            <div className="bg-orange-50 p-4 rounded-lg border border-orange-100 space-y-4">
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  {...register("isNewArrival")}
                  className="w-5 h-5 accent-black"
                />
                <label className="font-medium text-gray-700">
                  Mark as New Arrival
                </label>
              </div>

              <hr className="border-orange-200" />

              <div>
                <label className="label text-orange-800">Discount Offer</label>
                <div className="flex gap-2">
                  <select
                    {...register("discountType")}
                    className="p-2 border rounded bg-white w-1/2 text-sm"
                  >
                    <option value="NONE">No Offer</option>
                    <option value="PERCENTAGE">Percentage (%)</option>
                    <option value="FIXED">Fixed Amount (LKR)</option>
                  </select>

                  {watchedDiscountType !== "NONE" && (
                    <input
                      type="number"
                      {...register("discountValue")}
                      placeholder="Value"
                      className="p-2 border rounded w-1/2 text-sm"
                    />
                  )}
                </div>
              </div>

              {/* LIVE PREVIEW */}
              {watchedDiscountType !== "NONE" && Number(watchedPrice) > 0 && (
                <div className="bg-white p-2 rounded border border-orange-200 text-sm text-center">
                  <span className="text-gray-400 line-through mr-2">
                    Rs. {watchedPrice}
                  </span>
                  <span className="font-bold text-green-600">
                    Now Rs. {getDiscountedPrice().toFixed(2)}
                  </span>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* --- SECTION 3: CATEGORIZATION --- */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-700 border-b pb-2">
            Categorization
          </h2>
          <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
            <Controller
              name="categoryId"
              control={control}
              render={({ field }) => (
                <ParentSelector
                  key={`cat-${resetKey}`}
                  refreshTrigger={0}
                  onSelectionChange={(id) => field.onChange(id || "")}
                />
              )}
            />
          </div>
        </div>

        {/* --- SECTION 4: INVENTORY --- */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-700 border-b pb-2">
            Inventory & Variants
          </h2>
          <StockManager
            key={`stock-${resetKey}`}
            onUpdate={(data) => {
              // Update both sizeType and variants when stock manager changes
              setValue("sizeType", data.sizeType);
              setValue("variants", data.variants);
              setValue("stock", 0); // Reset base stock as per original logic
            }}
          />
        </div>

        {/* --- SUBMIT BUTTON --- */}
        <div className="pt-4">
          <button
            type="submit"
            disabled={mutation.isPending}
            className="w-full bg-black text-white py-4 rounded-lg text-lg font-semibold hover:bg-gray-800 transition disabled:opacity-50"
          >
            {mutation.isPending ? "Creating Product..." : "Publish Product"}
          </button>
        </div>

        {/* --- FEEDBACK MESSAGES --- */}
        {(mutation.isSuccess || mutation.isError) && (
          <div
            className={`p-4 text-center rounded-lg font-medium ${
              mutation.isSuccess
                ? "bg-green-100 text-green-800"
                : "bg-red-100 text-red-800"
            }`}
          >
            {mutation.isSuccess
              ? "✅ Product Created! Resetting form..."
              : `❌ Error: ${mutation.error?.message || "Something went wrong"}`}
          </div>
        )}
      </form>

      <style jsx>{`
        .label {
          display: block;
          margin-bottom: 0.5rem;
          font-size: 0.875rem;
          font-weight: 500;
          color: #374151;
        }
        .input-field {
          width: 100%;
          padding: 0.75rem;
          border: 1px solid #d1d5db;
          border-radius: 0.5rem;
          outline: none;
          transition: border-color 0.2s;
        }
        .input-field:focus {
          border-color: #2563eb;
          ring: 2px;
          ring-color: #bfdbfe;
        }
      `}</style>
    </div>
  );
}